apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: The infra team
spec:
  type: team
  profile:
    displayName: Infra team
    email: infrastructure@example.com
  children: []
  members: [raman]

